import { Hono } from "hono";
import path from "path";
import fs from "fs";
import { s3Storage } from "../services/s3Storage";

export type UpdateType = "installer" | "patch" | "extension" | "policy";

export interface ReleaseManifest {
  version: string;
  commit: string;
  updateType?: UpdateType;
  name?: string;
  productVersion?: string;
  filename?: string;
  s3Key?: string;
  downloadUrl: string;
  sha256hash?: string;
  sizeBytes?: number;
  sizeMB?: number;
  notes?: string;
  releasedAt: string;
  mandatory?: boolean;
  targetExtensionId?: string;
  extensionVersion?: string;
  policyConfig?: Record<string, any>;
}

const MANIFEST_PATH = path.resolve(__dirname, "../../release_manifest.json");
const RELEASES_DIR = path.resolve(__dirname, "../../releases");

if (!fs.existsSync(RELEASES_DIR)) {
  fs.mkdirSync(RELEASES_DIR, { recursive: true });
}
let currentRelease: ReleaseManifest = {
  version: "1.95.1",
  commit: "0c305f1b8afea035cdb283bef94edb88b7029f98",
  name: "Fvscode 1.95.1",
  productVersion: "1.95.1",
  filename: "Fvscode-UserSetup-x64.exe",
  s3Key: "releases/Fvscode-UserSetup-x64.exe",
  downloadUrl: "http://localhost:3000/v1/releases/Fvscode-UserSetup-x64.exe",
  notes:
    "Phiên bản chuẩn thi cử FPT University: tích hợp hệ thống giám sát thời gian thực và IEM widget.",
  releasedAt: new Date().toISOString(),
  mandatory: false,
};

try {
  if (fs.existsSync(MANIFEST_PATH)) {
    const raw = fs.readFileSync(MANIFEST_PATH, "utf8");
    currentRelease = { ...currentRelease, ...JSON.parse(raw) };
  } else {
    fs.writeFileSync(
      MANIFEST_PATH,
      JSON.stringify(currentRelease, null, 2),
      "utf8",
    );
  }
} catch (err) {
  console.warn(
    "[UpdateRouter] Could not read local release_manifest.json, using defaults:",
    err,
  );
}

export function getCurrentRelease(): ReleaseManifest {
  try {
    if (fs.existsSync(MANIFEST_PATH)) {
      const raw = fs.readFileSync(MANIFEST_PATH, "utf8");
      currentRelease = { ...currentRelease, ...JSON.parse(raw) };
    }
  } catch (err) {}
  return currentRelease;
}

export function saveReleaseManifest(manifest: ReleaseManifest) {
  currentRelease = { ...manifest };
  try {
    fs.writeFileSync(
      MANIFEST_PATH,
      JSON.stringify(currentRelease, null, 2),
      "utf8",
    );
  } catch (err) {
    console.error("[UpdateRouter] Failed to persist release manifest:", err);
  }
}

let lastS3CheckTime = 0;
const S3_CHECK_INTERVAL_MS = 30 * 1000;

export async function getLatestRelease(
  forceS3 = false,
): Promise<ReleaseManifest> {
  const now = Date.now();

  if (
    s3Storage.isAvailable() &&
    (forceS3 || now - lastS3CheckTime > S3_CHECK_INTERVAL_MS)
  ) {
    lastS3CheckTime = now;
    try {
      const s3Manifest = await s3Storage.getReleaseManifestFromS3();
      if (s3Manifest && s3Manifest.version && s3Manifest.commit) {
        currentRelease = {
          ...currentRelease,
          ...s3Manifest,
        };
        saveReleaseManifest(currentRelease);
        return currentRelease;
      }

      const s3Latest = await s3Storage.findLatestReleaseInS3();
      if (s3Latest) {
        currentRelease.filename = s3Latest.filename;
        currentRelease.s3Key = s3Latest.key;
        currentRelease.sizeBytes = s3Latest.size;
        saveReleaseManifest(currentRelease);
      }
    } catch (err: any) {
      console.warn(
        "[UpdateRouter] S3 release auto-discovery warning:",
        err?.message || err,
      );
    }
  }

  return getCurrentRelease();
}

export const updateRouter = new Hono();

/**
 * VS Code Native Update Endpoint
 * Target URL generated by AbstractUpdateService:
 *   ${productService.updateUrl}/api/update/${platform}/${quality}/${commit}
 * Example:
 *   GET /v1/api/update/win32-x64-user/stable/0c305f1b8afea035cdb283bef94edb88b7029f98
 */
updateRouter.get("/api/update/:platform/:quality/:commit", async (c) => {
  const { platform, quality, commit } = c.req.param();
  const isBg = c.req.query("bg") === "true";

  const release = await getLatestRelease();

  console.log(
    `[UpdateRouter] Check update received - Platform: ${platform}, Quality: ${quality}, Client Commit: ${commit}, Latest Commit: ${release.commit}, Background: ${isBg}`,
  );

  if (commit && commit.toLowerCase() === release.commit.toLowerCase()) {
    console.log(
      `[UpdateRouter] Client ${commit} is up-to-date. Returning 204.`,
    );
    return c.body(null, 204);
  }
  console.log(
    `[UpdateRouter] Update available! Client: ${commit} -> Latest: ${release.commit} (v${release.version})`,
  );

  const host = c.req.header("host") || "localhost:3000";
  const proto =
    c.req.header("x-forwarded-proto") ||
    (host.startsWith("localhost") ? "http" : "https");
  const filename = release.filename || "Fvscode-UserSetup-x64.exe";
  const downloadUrl = `${proto}://${host}/v1/releases/${filename}`;

  return c.json({
    url: downloadUrl,
    name: release.name || `Fvscode ${release.version}`,
    version: release.commit,
    productVersion: release.productVersion || release.version,
    sha256hash: release.sha256hash,
    notes: release.notes,
  });
});

/**
 * Release Binary File Downloader
 * 1. Serves from local releases/ folder if file is stored on disk
 * 2. Or streams directly from S3 (releases/:filename) if running on deployed proxy
 */
updateRouter.get("/releases/:filename", async (c) => {
  const filename = c.req.param("filename");
  const safeFilename = path.basename(filename);
  const localFilePath = path.join(RELEASES_DIR, safeFilename);

  if (fs.existsSync(localFilePath)) {
    const stat = fs.statSync(localFilePath);
    return new Response(Bun.file(localFilePath), {
      headers: {
        "Content-Type": "application/octet-stream",
        "Content-Disposition": `attachment; filename="${safeFilename}"`,
        "Content-Length": stat.size.toString(),
      },
    });
  }

  if (s3Storage.isAvailable()) {
    console.log(
      `[UpdateRouter] File not local, fetching from S3: releases/${safeFilename}...`,
    );
    const s3Object = await s3Storage.getReleaseStream(safeFilename);
    if (s3Object && s3Object.stream) {
      const headers: Record<string, string> = {
        "Content-Type": s3Object.contentType || "application/octet-stream",
        "Content-Disposition": `attachment; filename="${safeFilename}"`,
      };
      if (s3Object.contentLength) {
        headers["Content-Length"] = s3Object.contentLength.toString();
      }

      return new Response(s3Object.stream, { headers });
    }
  }

  return c.json(
    { error: `Release binary ${safeFilename} not found locally or on S3.` },
    404,
  );
});

/**
 * Query current published release
 */
updateRouter.get("/release/current", async (c) => {
  const release = await getLatestRelease();
  const host = c.req.header("host") || "localhost:3000";
  const proto =
    c.req.header("x-forwarded-proto") ||
    (host.startsWith("localhost") ? "http" : "https");

  // Dynamically ensure downloadUrl matches client connection host if pointing to releases/
  let downloadUrl = release.downloadUrl;
  if (downloadUrl && downloadUrl.includes("/releases/")) {
    const filename = path.basename(downloadUrl);
    downloadUrl = `${proto}://${host}/v1/releases/${filename}`;
  }

  return c.json({
    success: true,
    release: {
      ...release,
      downloadUrl,
    },
    s3Enabled: s3Storage.isAvailable(),
  });
});

updateRouter.get("/admin/release/current", async (c) => {
  const release = await getLatestRelease();
  return c.json({
    success: true,
    release,
    s3Enabled: s3Storage.isAvailable(),
  });
});

/**
 * Force sync from S3 releases folder
 */
updateRouter.post("/release/sync-s3", async (c) => {
  const release = await getLatestRelease(true);
  return c.json({
    success: true,
    message: "Synchronized with S3 release repository successfully.",
    release,
  });
});

/**
 * Publish or update latest release manually (Supports all 4 update types: installer, patch, extension, policy)
 */
updateRouter.post("/release/set-latest", async (c) => {
  try {
    const body = await c.req.json();
    if (!body.version || !body.commit) {
      return c.json({ error: "Missing required fields: version, commit" }, 400);
    }

    const updated: ReleaseManifest = {
      version: String(body.version).trim(),
      commit: String(body.commit).trim(),
      updateType:
        (body.updateType as UpdateType) ||
        currentRelease.updateType ||
        "installer",
      name: body.name || `Fvscode ${body.version}`,
      productVersion: body.productVersion || body.version,
      filename:
        body.filename || currentRelease.filename || "Fvscode-UserSetup-x64.exe",
      downloadUrl: body.downloadUrl
        ? String(body.downloadUrl).trim()
        : currentRelease.downloadUrl,
      sha256hash: body.sha256hash?.trim() || currentRelease.sha256hash,
      sizeBytes: body.sizeBytes ?? currentRelease.sizeBytes,
      sizeMB: body.sizeMB ?? currentRelease.sizeMB,
      notes: body.notes || currentRelease.notes || "",
      releasedAt: new Date().toISOString(),
      mandatory: Boolean(body.mandatory),
      targetExtensionId:
        body.targetExtensionId || currentRelease.targetExtensionId,
      extensionVersion:
        body.extensionVersion || currentRelease.extensionVersion,
      policyConfig: body.policyConfig || currentRelease.policyConfig,
    };

    saveReleaseManifest(updated);
    console.log(
      `[UpdateRouter] Published new release: v${updated.version} (${updated.commit}), Type: ${updated.updateType}`,
    );

    return c.json({
      success: true,
      message: `Published ${updated.updateType} release successfully.`,
      release: currentRelease,
    });
  } catch (err: any) {
    return c.json({ error: err.message || "Failed to update release" }, 500);
  }
});
